// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2) {
  return window['go']['main']['App']['Create'](arg1, arg2);
}

export function DeleteTaskByID(arg1, arg2) {
  return window['go']['main']['App']['DeleteTaskByID'](arg1, arg2);
}

export function GetAllTasks(arg1) {
  return window['go']['main']['App']['GetAllTasks'](arg1);
}

export function GetTaskByID(arg1, arg2) {
  return window['go']['main']['App']['GetTaskByID'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function MarkAsDone(arg1, arg2) {
  return window['go']['main']['App']['MarkAsDone'](arg1, arg2);
}

export function MarkAsUndone(arg1, arg2) {
  return window['go']['main']['App']['MarkAsUndone'](arg1, arg2);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}
