// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Create(arg1:number,arg2:string):Promise<number>;

export function DeleteTaskByID(arg1:number,arg2:number):Promise<void>;

export function GetAllTasks(arg1:number):Promise<Array<models.Task>>;

export function GetTaskByID(arg1:number,arg2:number):Promise<models.Task>;

export function Login(arg1:string,arg2:string):Promise<models.AuthResponse>;

export function MarkAsDone(arg1:number,arg2:number):Promise<void>;

export function MarkAsUndone(arg1:number,arg2:number):Promise<void>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<models.AuthResponse>;
